### ISSUE TITLE
请问数据集什么时候能发布呢

### ISSUE THREAD

**Issue by HQ-LV** [PointCloudYC/CTS#1]

**Comment by PointCloudYC** [comment]
Thanks for your attention! We will organize the code and dataset A.S.A.P and try to release them in mid. Dec.

**Comment by HQ-LV** [comment]
OK. thanks for replying！





------------------ 原始邮件 ------------------
发件人: Chao YIN 尹超 ***@***.***&gt;
发送时间: 2022年12月1日 18:00
收件人: PointCloudYC/CTS ***@***.***&gt;
抄送: HQ-LV ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PointCloudYC/CTS] 请问数据集什么时候能发布呢 (Issue #1)





 
Thanks for your attention! We will organize the code and dataset A.S.A.P and try to release the code and dataset in Mid. Dec.

**Comment by PointCloudYC** [comment]
The dataset and code released
